[build]
  publish = "."

[build.processing]
  skip_processing = true

# 表单设置
[[forms]]
  name = "registration"

# 处理SPA路由
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# 重定向规则
[[redirects]]
  from = "/admin"
  to = "/admin.html"
  status = 200 